### ISSUE TITLE
blueprint generating errors when running automation

### ISSUE THREAD

**Issue by armandomuassab** [PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor#162]
When executing automation several errors are generated

Logger: homeassistant.helpers.template
Source: helpers/template.py:1377
First occurred: 15:45:21 (1 occurrences)
Last logged: 15:45:21

Template variable error: 'dict object' has no attribute 'to_state' when rendering '{% if trigger.to_state.state in ["unavailable", "unknown", "docked"] %} camera.turn_off {% else %} camera.turn_on {% endif %}'

Logger: homeassistant.components.automation.vacuum_camera_disable_update_when_docked
Source: helpers/script.py:1344
Integration: Automação (documentation, issues)
First occurred: 15:45:21 (1 occurrences)
Last logged: 15:45:21

vacuum camera disable update when docked: Error executing script. Error for call_service at pos 1: Error rendering service name template: UndefinedError: 'dict object' has no attribute 'to_state'

Logger: homeassistant.components.automation.vacuum_camera_disable_update_when_docked
Source: components/automation/__init__.py:517
Integration: Automação (documentation, issues)
First occurred: 15:45:21 (1 occurrences)
Last logged: 15:45:21

Error while executing automation automation.vacuum_camera_disable_update_when_docked: Error rendering service name template: UndefinedError: 'dict object' has no attribute 'to_state'

**Comment by Bellavista** [comment]
the same for me
Hassio Home Assistant 2021.9.4
this is may automation:
`alias: AGGIORNA MAPPA CERCHIO SOLO QUANDO ATTIVO
description: ''
**trigger:
  - platform: state
    entity_id: vacuum.cerchio
    attribute: status**
condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
action:
  - service: |
      {% if trigger.to_state.state in ["unavailable", "unknown", "docked"] %}
        camera.turn_off
      {% else %}
        camera.turn_on
      {% endif %}
    entity_id: camera.mappa_cerchio
mode: restart`

**unspecified trigger state does not work**

**Comment by PiotrMachowski** [comment]
@halfbakery, can you check it out? I don't use this blueprint

**Comment by halfbakery** [comment]
It took a long time, but I've managed to update my Home Assistant finally :-)

It seems the generated automation works correctly when invoked by a trigger, but prints an error when invoked by the user (e.g. pressing the `RUN ACTIONS` button or similar). It's quite logical, because the `from_state` and `to_state` fields are missing in this case.

Could you confirm this? Please go into `Configuration` -> `Automations `-> _press the trace button of the generated automation_. Select `Trace Timeline` and check whether the invocation is `triggered by state` or `triggered manually`.

**Comment by PiotrMachowski** [comment]
Problem should be solved in v2.1.2
